ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: 10G
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;

      rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
      rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }
  tls:
     - secretName: ""
       hosts:
         - project.retail-consult.by

nextcloud:
  host: project.retail-consult.by
  existingSecret:
    enabled: true
    secretName: nc-secret
    usernameKey: nc-user
    passwordKey: nc-pass
    tokenKey: ""
    smtpUsernameKey: ""
    smtpPasswordKey: ""
    smtpHostKey: ""
  objectStore:
    s3:
      enabled: true
      region: "ru-central1"
      usePathStyle: true
      existingSecret: nc-secret
      secretKeys:
        host: s3host
        accessKey: s3key
        secretKey: s3secret
        bucket: s3bucket
        sse_c_key: ""
  defaultConfigs:
    redis.config.php: false

  configs:
    caching.config.php: |-
      <?php
      $CONFIG = array (
        'memcache.local' => '\OC\Memcache\APCu',
        'memcache.distributed' => '\OC\Memcache\Memcached',
        'memcache.locking' => '\OC\Memcache\Redis',
        'filelocking.enabled' => 'true',
        'redis' => array (
          'host' => 'redis-master',
          'port' => 6379,
          'timeout' => 0.0,
        ),
        'memcached_servers' => array(
          array('memcached', 11211),
        ),
      );
    logging.config.php: |-
      <?php
      $CONFIG = array (
        'log_type' => 'file',
        'logfile' => 'nextcloud.log',
        'loglevel' => 2,
        'logdateformat' => 'F d, Y H:i:s'
        );

internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: mysql
  host: "pxc-db-haproxy"
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: nc-secret
    usernameKey: db-user
    passwordKey: db-pass

metrics:
  enabled: true
  replicaCount: 1
  serviceMonitor:
    enabled: true
    namespace: monitoring

collabora:
  enabled: false
 

persistence:
  enabled: true
  storageClass: yc-network-hdd
  size: 2Gi
