apiVersion: v1
kind: Secret
metadata:
  name: loki-s3
  namespace: monitoring
type: Opaque
data:
  s3-key: !!!S3_KEY!!!
  s3-secret: !!!S3_SECRET!!!
---
apiVersion: v1
data:
  monitor: !!!DB_PASS!!!
  operator: !!!DB_PASS!!!
  proxyadmin: !!!DB_PASS!!!
  replication: !!!DB_PASS!!!
  root: !!!DB_PASS!!!
  xtrabackup: !!!DB_PASS!!!
kind: Secret
metadata:
  name: pxc-db-secrets
  namespace: app


