apiVersion: v1
kind: Secret
metadata:
  name: loki-s3
  namespace: monitoring
type: Opaque
data:
  s3-key: !!!S3_KEY!!!
  s3-secret: !!!S3_SECRET!!!
  s3-bucket: !!!S3_BUCKET_LOKI!!!
---
apiVersion: v1
data:
  monitor: !!!DB_PASS!!!
  operator: !!!DB_PASS!!!
  proxyadmin: !!!DB_PASS!!!
  replication: !!!DB_PASS!!!
  root: !!!DB_PASS!!!
  xtrabackup: !!!DB_PASS!!!
kind: Secret
metadata:
  name: pxc-db-secrets
  namespace: app
---
apiVersion: v1
data:
  nc-user: YWRtaW4=
  nc-pass: !!!DB_PASS!!!
  db-user: cm9vdA==
  db-pass: !!!DB_PASS!!!
  s3key: !!!S3_KEY!!!
  s3secret: !!!S3_SECRET!!!
  s3host: c3RvcmFnZS55YW5kZXhjbG91ZC5uZXQ=
  s3bucket: !!!S3_BUCKET_NC!!!
kind: Secret
metadata:
  name: nc-secret
  namespace: app


