name: Run Cluster Script

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  run-cluster-script:
    # if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
        else
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
        fi
        echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

    - name: Check if cluster.py was changed
      id: check-cluster
      run: |
        if echo "${{ env.CHANGED_FILES }}" | grep -q "scripts/cluster.py"; then
          echo "changed=true" >> $GITHUB_ENV
        else
          echo "changed=false" >> $GITHUB_ENV
        fi

    - name: Run cluster script
      if: env.changed == 'true'
      env:
        SECRET: ${{ secrets.SECRET }}
        CLOUD: ${{ secrets.CLOUD }}
        FOLDER: ${{ secrets.FOLDER }}
      run: |
        echo $SECRET
        python3 scripts/cluster.py
