apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.1
    chart: ingress-nginx
    helm:
      valueFiles:
        - $values/values/nginx-values.yaml
  - ref: values
    repoURL: https://github.com/Losyaka/project-kube.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
