apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 20.11.3
    chart: redis
    helm:
      valueFiles:
        - $values/values/redis-values.yaml
  - ref: values
    repoURL: https://github.com/Losyaka/project-kube.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true